apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bk-app
  name: bk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bk-app
  template:
    metadata:
      labels:
        app: bk-app
    spec:
      containers:
      - name: myapp-container
        image: busybox:1.28
        command: ['sh', '-c', 'sleep 10']