apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: processor
        image: busybox
        command: ["sh",  "-c", "sleep 10"]
      restartPolicy: Never
