apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bk-app
  name: bk-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bk-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: bk-app
    spec:
      containers:
      - image: busybox
        name: bk-rest-app
        command:
          - ["sleep", "10"]
